fix: build error on 6.8 kernel due to
The error:
media_build/v4l/ccs-core.c:668:21: error: too many arguments to function 'pm_runtime_get_if_active'

  668 |         pm_status = pm_runtime_get_if_active(&client->dev, true);

      |                     ^~~~~~~~~~~~~~~~~~~~~~~~